/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package projetAntoine.ihm;

import java.awt.event.ItemEvent;
import javax.swing.JOptionPane;
import projetAntoine.entites.CEntitees;
import projetAntoine.entites.CFormation;
import projetAntoine.persistance.CPersistance;

/**
 *
 * @author Antoine Liégard, liegard.antoine35@gmail.com
 */
public class JPanelEditFormation extends javax.swing.JPanel {

    /**
     * Creates new form JPanelInsertEtudiant
     */
    protected CEntitees entitees;
    protected CPersistance persistance;

    public JPanelEditFormation(CEntitees entitees, CPersistance persistance) {
        this.entitees = entitees;
        this.persistance = persistance;
        initComponents();

        CFormation[] tabFormations = new CFormation[(entitees.getListeFormations().listeFormations.size())];

        for (int i = 0; i < tabFormations.length; i++) {
            if (i != tabFormations.length) {
                tabFormations[i] = entitees.getListeFormations().listeFormations.get(i);
            } else {
                tabFormations[i] = null;
            }
        }
        
        this.ComboFormation.setModel(new javax.swing.DefaultComboBoxModel(tabFormations));
        this.ComboFormation.setRenderer(new CComboBoxRenderer());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ButtonDelete = new javax.swing.JButton();
        mainLabel = new javax.swing.JLabel();
        LabelLibellé = new javax.swing.JLabel();
        TextFieldLibellé = new javax.swing.JTextField();
        ButtonInsert = new javax.swing.JButton();
        ButtonCancel = new javax.swing.JButton();
        TextFieldOption = new javax.swing.JTextField();
        LabelOption = new javax.swing.JLabel();
        ButtonDelete1 = new javax.swing.JButton();
        ComboFormation = new javax.swing.JComboBox<>();

        ButtonDelete.setText("Supprimer");
        ButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonDeleteActionPerformed(evt);
            }
        });

        setMinimumSize(new java.awt.Dimension(150, 150));
        setPreferredSize(new java.awt.Dimension(150, 500));

        mainLabel.setText("Modifier formation");

        LabelLibellé.setText("Libellé diplome *");

        TextFieldLibellé.setMinimumSize(new java.awt.Dimension(50, 30));
        TextFieldLibellé.setName(""); // NOI18N
        TextFieldLibellé.setPreferredSize(new java.awt.Dimension(50, 30));

        ButtonInsert.setText("Modifier");
        ButtonInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonInsertActionPerformed(evt);
            }
        });

        ButtonCancel.setText("Annuler");
        ButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ButtonCancelActionPerformed(evt);
            }
        });

        TextFieldOption.setMinimumSize(new java.awt.Dimension(50, 30));
        TextFieldOption.setName(""); // NOI18N
        TextFieldOption.setPreferredSize(new java.awt.Dimension(50, 30));

        LabelOption.setText("Option diplome");

        ButtonDelete1.setText("Supprimer");

        ComboFormation.setMaximumSize(new java.awt.Dimension(31, 24));
        ComboFormation.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                ComboFormationItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(mainLabel)
                                .addGap(18, 18, 18)
                                .addComponent(ComboFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(LabelLibellé)
                            .addComponent(TextFieldLibellé, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(LabelOption)
                            .addComponent(TextFieldOption, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 109, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ButtonInsert)
                        .addGap(18, 18, 18)
                        .addComponent(ButtonCancel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(ButtonDelete1)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mainLabel)
                    .addComponent(ComboFormation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelLibellé)
                    .addComponent(LabelOption))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextFieldLibellé, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextFieldOption, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ButtonInsert)
                    .addComponent(ButtonCancel)
                    .addComponent(ButtonDelete1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ButtonInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonInsertActionPerformed
        String libelle = TextFieldLibellé.getText();
        String option = TextFieldOption.getText();
        CFormation formation = new CFormation(libelle, option);
        persistance.getTableFormation().insererFormation(formation);
        entitees.initEntitée(persistance);
        this.setVisible(false);
    }//GEN-LAST:event_ButtonInsertActionPerformed

    private void ButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonCancelActionPerformed
        this.setVisible(false);

//        //pas obligatoire, pour recharger le layout
//        this.validate();
    }//GEN-LAST:event_ButtonCancelActionPerformed

    private void ButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ButtonDeleteActionPerformed
        CFormation formation = (CFormation) ComboFormation.getSelectedItem();
        persistance.getTableFormation().supprimerFormation(formation);
        JOptionPane.showMessageDialog(null, "Formation supprimé");
        entitees.initEntitée(persistance);
        // todo besoin de recharger 
    }//GEN-LAST:event_ButtonDeleteActionPerformed

    private void ComboFormationItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_ComboFormationItemStateChanged
        if ((evt.getStateChange() == ItemEvent.SELECTED)) {
            CFormation selection = (CFormation) ComboFormation.getSelectedItem();
            TextFieldLibellé.setText(selection.getLibelleDiplome());
            TextFieldOption.setText(selection.getOptionDiplome());

        }
    }//GEN-LAST:event_ComboFormationItemStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ButtonCancel;
    private javax.swing.JButton ButtonDelete;
    private javax.swing.JButton ButtonDelete1;
    private javax.swing.JButton ButtonInsert;
    private javax.swing.JComboBox<String> ComboFormation;
    private javax.swing.JLabel LabelLibellé;
    private javax.swing.JLabel LabelOption;
    private javax.swing.JTextField TextFieldLibellé;
    private javax.swing.JTextField TextFieldOption;
    private javax.swing.JLabel mainLabel;
    // End of variables declaration//GEN-END:variables

    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
     */
}
